### ISSUE TITLE
Adding voters via CSV requires to sign a transaction per voter

### ISSUE THREAD

**Issue by anadi2311** [gitcoinco/easy-retro-pgf#197]
When admin uploads a voters list via CSV, metamask trigger a transaction to approve every voter one by one. If someone plans to  upload thousands of voters, then they have to do it thousands of time which is not realistic. Can you support a bulk approval? (like what already happens if voters are added via text box)

**Comment by thomasheremans** [comment]
To add a bit more color: I believe there is a way to do it in bulk as when uploading multiple voters via the UI (see screenshot), only one txn is required. We use CSV import as have custom voting power per voter.

Thanks

![Screenshot 2024-12-09 at 18 52 53](https://github.com/user-attachments/assets/b56b7f34-4f0d-4b9b-9a34-e6d59f3f6817)
