### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by samajammin** [gitcoinco/easy-retro-pgf#22]
Hey folks!

I remember reading your [OP forum post](https://gov.optimism.io/t/easyretropgf-xyz-run-your-own-optimism-style-rpgf-round/7359) where you mention that you're:
> now open sourcing it and releasing it for others’ use

...but I'm noticing there's no actual license on this repo. 

Could you please [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) (e.g. MIT) to clarify this?

For context, we're [working on a fork](https://github.com/privacy-scaling-explorations/maci-rpgf/) and we intend to open source our code as well (in additional to merging any improvements upstream back to you, if that's of interest).

Thanks!

**Comment by carlbarrdahl** [comment]
Thank you @samajammin! I've added the MIT license.

**Comment by samajammin** [comment]
Thanks @carlbarrdahl 🙏
