### ISSUE TITLE
Thomas from Obol's issues

### ISSUE THREAD

**Issue by owocki** [gitcoinco/easy-retro-pgf#9]
Quick other feedback piece when trying to add projects
- Previous project details load while it has already been registered
- I get prompted to sign the registration even if not click on the button at regular intervals
- It can take time for the project to appear on on the review page so might be worth adding a disclaimer to avoid people logging it twice. It could be worth checking for duplicates

**Comment by carlbarrdahl** [comment]
Fixed in 23312ff5259ba5680798ec615be11efd7de7c58b
